### ISSUE TITLE
problem adding a connection

### ISSUE THREAD

**Issue by Abhishek-N** [DevDataPlatform/DDP_backend#150]
When I try to create a connection, I receive a 500 error response. Here’s a screenshot of the error message:

<img width="929" alt="Screenshot 2023-06-09 at 2 51 46 PM" src="https://github.com/DevDataPlatform/DDP_backend/assets/35729337/5b989570-20a1-4f18-8b6b-a734063ef9b5">

**Comment by fatchat** [comment]
Hi @Abhishek-N , if you tell me when this happened (date and time) I will be able to look in the logs. Also include any other information which would help me find the relevant log messages e.g. org name, for now I will search for `surveycto_1` and `stir_connection_1` and see what I can find. Thanks
