### ISSUE TITLE
Uniformize the variable names

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/DDP_backend#16]
Pick a naming convention for functions, classes and variables

Update all existing code

**Comment by fatchat** [comment]
Also document this in the README

**Comment by fatchat** [comment]
also fix import errors / names

**Comment by dlobo** [comment]
should we just use standard python naming convention from PEP 8

https://peps.python.org/pep-0008/

we should not reinvent this. You can then run a pep8 style checker to ensure that code is as recommended

**Comment by fatchat** [comment]
ok we will follow pep 8, ishan please let us know how to configure what plugin for vscode

**Comment by Ishankoradia** [comment]
Sure. Have used pylint(follows pep8) and made a PR
