### ISSUE TITLE
make sure secrets don't appear in logfiles

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/DDP_backend#199]
can we use https://docs.pydantic.dev/dev-v2/usage/types/secrets/

**Comment by Ishankoradia** [comment]
@fatchat the pydantic offers two secret types: `SecretStr` and `SecretField` . But in our case we have a general `config` dictionary (we dont exactly know the keys inside them) which has the credentials and using `Dict[str, SecretStr]` since it changes the type of that config field dictionary to something else. Which then requires adding `allow_arbirtrary_types=True` in the schema classes.

**Comment by Ishankoradia** [comment]
@fatchat another way to prevent logging secrets or credentials is to add custom logic to a custom handler before logging anything. However, we won't definitively know if the value being logged is a secret or not

**Comment by fatchat** [comment]
Verified: DDP_backend, searched for "logger." in VS Code and went through the 94 results one by one
we log
- fixed strings
- directories and filenames
- airbyte object ids
- prefect object ids
- prefect block names
- git commands - though not gitrepo tokens since those are not stored with the commands in the dbt core-op blocks
- airbyte responses - in which secrets are masked by airbyte
- stack traces which don't show variable values

Specifically checked
- `post_prefect_dbt_core_block`
- `post_organization_warehouse`
- `post_organization_user`
- `post_reset_password`

Verified: 145 occurences in prefect-proxy. Made sure to check 
- `post_secret_block`
- `put_dbtcore_bigquery`
- `put_dbtcore_postgres`
- `update_postgres_credentials`
- `update_bigquery_credentials`
- `create_secret_block`
- `prefect_post`
- `prefect_patch`
- `prefect_get`

Found logging of secrets in
- `_create_dbt_cli_profile` 
and its callers:
- `create_dbt_core_block`
- `post_dbtcore`

and removed via https://github.com/DevDataPlatform/prefect-proxy/issues/64

**Comment by Ishankoradia** [comment]
@fatchat went through the both the repos again. Don't see anymore secrets being logged. You have covered everything. From now on, we should make sure that we don't log any secrets while coding and reviewing the PRs.
