### ISSUE TITLE
Review the recent Airbyte API wrapper code

### ISSUE THREAD

**Issue by fatchat** [DevDataPlatform/DDP_backend#2]
I just committed 

 https://github.com/DevDataPlatform/ddp-ui-001/commit/7512e0a33dcef9c622d7e07b16f0d6c9f9a88e84

(This is the last commit I'm making to the master branch)

@Ishankoradia would you please refactor according to what we discussed last week i.e. 
- wrapping route handlers in try-catch blocks
- using your helper functions api and api_error

**Comment by vinod-rajasekaran** [comment]
Moving out of this sprint - will discuss when you are back and discuss how we are going to be using these apis versus the earlier Api structure done by Ishan.

**Comment by fatchat** [comment]
superseded by issues 16-18
