### ISSUE TITLE
Prefect dbt test failure should be recorded as warning

### ISSUE THREAD

**Issue by Ishankoradia** [DevDataPlatform/DDP_backend#219]
Currently, when dbt tests fail prefect throws an error and the entire pipeline is recorded as failure. Can we change the behaviour such that when the dbt tests fail, the pipeline only throws a warning.

**Comment by fatchat** [comment]
Related: https://github.com/DevDataPlatform/prefect-proxy/issues/62

**Comment by fatchat** [comment]
We can configured `dbt test` failures to show up as successes

We might create a new state following https://github.com/PrefectHQ/prefect/issues/10291#issuecomment-1682350743 and configure a discord notification for it
