### ISSUE TITLE
Need to add new feature for the prefect(SHRI)

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#236]
- For running the SHRI pipeline the NGO wants the pipeline to run at 10 PM IST. Currently, this is not there.
- Similarly when selecting weekly, we should be able to select day of the week. Current default is Monday.

**Comment by nairabhishek73** [comment]
1. https://ddpstagingui.projecttech4dev.org/pipeline/orchestrate showing 1am everyday.
2. https://ddpstagingui.projecttech4dev.org/pipeline is showing 6:30am
@fatchat
