### ISSUE TITLE
unable to add google sheets source

### ISSUE THREAD

**Issue by jakejh** [DevDataPlatform/DDP_backend#278]
I first tried using the service account method, then just made the google sheet viewable to anyone with the link. Still gives the error "Failed to connect. Please check your credentials."

**Comment by fatchat** [comment]
`2023-08-16 16:39:49 INFO i.a.w.g.DefaultCheckConnectionWorker(run):114 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@7040e49e[status=failed,message=Config validation error: None is not of type 'string']`


thanks jake. it looks like we're missing sending something to airbyte. i'm guessing you sent the link to the sheet, did you also send service account credentials? 

airbyte requires credentials, whether via a service account or using an oauth token - see these two screenshots 

if you're authenticating via a service account you'll need to provide the usual JSON key which google provides

if you did all this and it still didn't work please let me know


![Image](https://github.com/DevDataPlatform/DDP_backend/assets/2160416/2b81761d-0f20-44c2-9e59-65793063d3cd)



![Image](https://github.com/DevDataPlatform/DDP_backend/assets/2160416/e51cb8b6-6490-410a-88e7-b4cdc1112405)

**Comment by jakejh** [comment]
Yes, I did all that. In addition, the airbyte connector documentation says you can also make the google sheet viewable to anyone with a link, in which case the service account credentials are not required. That didn't work either.

**Comment by jakejh** [comment]
Those screenshots do not match what I see in the ddp ui, by the way.

**Comment by fatchat** [comment]
No those screenshots are straight from Airbyte. If the Airbyte docs say that you don't need service account credentials if the sheet is public, try entering `{}`

**Comment by fatchat** [comment]
and if that works we can make our platform send that empty `{}` over to airbyte

i'll test this myself tomorrow with a public google sheet

**Comment by jakejh** [comment]
Nope, doesn't work. Same error message.

**Comment by fatchat** [comment]
Oh are you talking about the part in

https://docs.airbyte.com/integrations/sources/google-sheets/

where it says “
If your spreadsheet is viewable by anyone with its link, no further action
is needed.”

?

You still need to set up a service account, and you still need the Project
Viewer permission. What you don’t need for a publicly viewable sheet is to
give the SA access to this particular sheet

If the documentation you saw was different please link to it here so I can
see what they’re taking about

**Comment by jakejh** [comment]
Ah, fixed it. The problem was I hadn't enabled the Google Sheets API for this particular Google Cloud project.
