### ISSUE TITLE
Weird issue on production for normalization and raw

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#288]
So on production when Jake was testing Surveycto and choose to do the normalization and I checked in the airbyte UI it was still showing the raw but when we did run the sync it did run the normalization but when we saw it in the UI it was checked as Raw. Little confusing for Jake

**Comment by fatchat** [comment]
Related: #272 

We saw this with STiR remember, I thought it was a problem with Dalgo <-> Airbyte but now you're saying Airbyte did the normalization ... so now I'm thinking it's a problem with Airbyte

**Comment by siddhant3030** [comment]
@fatchat Let's test this properly. My only concern is when it changes to just raw then what will happen? does incremental will still work? which I forgot to test yesterday

**Comment by fatchat** [comment]
we found that part of the issue was that in the "edit connection" window we always showed "raw", this has been fixed as part of PR [#312](https://github.com/DevDataPlatform/webapp/pull/312)

remaining to check: airbyte should have the right configuration

**Comment by fatchat** [comment]
hi @siddhant3030 

in the staging STiR account [773de53f-579c-4c2e-99c7-bf72966d6cc3]

i created two new connections using the dalgo UI: "raw" and "norm"

and verified in "transformation" tab of airbyte's UI that they were "Raw data" and "Normalized tabular data" respectively

=> closing

**Comment by nairabhishek73** [comment]
Is this resolved? @siddhant3030
