### ISSUE TITLE
Airbyte server block name saved in db is different from the airbyte server block name in prefect

### ISSUE THREAD

**Issue by Ishankoradia** [DevDataPlatform/DDP_backend#290]
I created an org with the following the name `STiR_ishan`. 

In `airbyte_helpers.py`, the block name is slugified and becomes `stir_ishan-airbyte-server`
<img width="975" alt="Screenshot 2023-08-21 at 3 47 39 PM" src="https://github.com/DevDataPlatform/DDP_backend/assets/39583356/134f8f79-2b40-44c9-b2cc-e419ce20ffb3">

This block name is actually sent to prefect_proxy to create a block in prefect. However, there is another level of slugifcation/cleanup that is being done in prefect proxy. 

```service.py```
<img width="701" alt="Screenshot 2023-08-21 at 3 50 57 PM" src="https://github.com/DevDataPlatform/DDP_backend/assets/39583356/c84be576-2c29-473c-b3b6-6d9d5b8026d8">

```helpers.py```
<img width="701" alt="Screenshot 2023-08-21 at 3 51 45 PM" src="https://github.com/DevDataPlatform/DDP_backend/assets/39583356/4e0fc77a-3994-454c-947b-12fcdeca4de4">

This removes the underscore `_` so the block name that is stored in prefect is `stirishan-airbyte-server`. 
Hence ```stirishan-airbyte-server !== stir_ishan-airbyte-server```

**Comment by fatchat** [comment]
you are correct but is there a bug or is it just confusing

**Comment by fatchat** [comment]
sneaking into this issue: change connection failure message to "Failed to connect- please check details entered"
