### ISSUE TITLE
We can remove the logs tab from the connection page?

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#302]
Let's discuss this more but I think we can remove the logs from the connection page because the user cannot see it if it changes the tab or refreshes it and also it looks pretty bad at the bottom. We can give more info later about the syncs and all. Happy to discuss and plan it.

**Comment by siddhant3030** [comment]
@Abhishek-N

**Comment by fatchat** [comment]
this will be covered by https://github.com/DevDataPlatform/webapp/issues/255
