### ISSUE TITLE
Survey CTO is faliing in the platform. 

### ISSUE THREAD

**Issue by siddhant3030** [DevDataPlatform/DDP_backend#98]
This is the error we get. 

What we're able to do is. We can add the source for SurveyCTO and add the destination also. But sync is not working. 

```

Traceback (most recent call last):
  File "/home/ddp/DDP_backend/venv/lib/python3.10/site-packages/ninja/operation.py", line 104, in run
    result = self.view_func(request, **values)
  File "/home/ddp/DDP_backend/ddpui/api/client/airbyte_api.py", line 449, in post_airbyte_connection
    airbyte_conn = airbyte_service.create_connection(org.airbyte_workspace_id, payload)
  File "/home/ddp/DDP_backend/ddpui/ddpairbyte/airbyte_service.py", line 258, in create_connection
    sourceschemacatalog = get_source_schema_catalog(
  File "/home/ddp/DDP_backend/ddpui/ddpairbyte/airbyte_service.py", line 154, in get_source_schema_catalog
    raise Exception("Failed to get source schema catalogs")
Exception: Failed to get source schema catalogs
```

**Comment by fatchat** [comment]
is this what ishan encountered yesterday

running the airbyte command manually also failed, the http response from survey CTO was not parseable as JSON

he's supposed to put `print` statements into the connector at the relevant points, rebuild the container and run it again

running the connector python code directly succeeded... that's all i know

**Comment by siddhant3030** [comment]
@fatchat This is when we were using the platform to run the sync. Also, I have a question if there are multiple streams how are we dealing with that? I didn't see anything which will show that.

**Comment by siddhant3030** [comment]
Also, the sync is working fine. Just tested it.

**Comment by fatchat** [comment]
@Ishankoradia please meet siddhanth tomorrow and update him. put the logging messages into the python connector before you meet so he can help you build the container

**Comment by fatchat** [comment]
> is this what ishan encountered yesterday
> 
> running the airbyte command manually also failed, the http response from survey CTO was not parseable as JSON
> 
> he's supposed to put `print` statements into the connector at the relevant points, rebuild the container and run it again
> 
> running the connector python code `main.py discover` directly succeeded... that's all i know

@siddhant3030 
i should have clarified that "running the airbyte command manually" referred to running schema discovery

you'll see that referenced in the original error message the platform reported after airbyte didn't provide the schema catalog

you hit the failure at the time of setting up the connection not at the time of syncing - you didn't even have a connection to sync

when you guys meet please ensure that you are running the commands on the same airbyte deployment otherwise you will get more confused

let me know if you don't sort it out quickly

**Comment by siddhant3030** [comment]
We define a schema when we make the connection. We have written a whole code for that where it fetches all the data and create a schema out of it. This happens while making the connection. I think @Ishankoradia is familiar with it.

**Comment by siddhant3030** [comment]
This is fixed. So I'm closing this
